FROM ubuntu
RUN apt-get update
RUN apt-get install -y procps nano curl gnupg apt-transport-https gnupg2 inotify-tools python3-docker python3-setuptools python3-pip
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
RUN apt-get update
RUN echo "deb https://packages.wazuh.com/4.x/apt/ stable main" > /etc/apt/sources.list.d/wazuh.list
RUN WAZUH_MANAGER="wazuh.manager" apt-get install -y wazuh-agent
RUN update-rc.d wazuh-agent defaults 95 10
RUN service wazuh-agent start
COPY server.py /server.py
RUN apt-get install -y gcc python3-dev libpq-dev musl-dev
RUN apt-get update
RUN pip3 install psycopg2-binary --break-system-packages

CMD sh -c "service wazuh-agent start; python3 /server.py; sleep 1;"
