FROM ubuntu
RUN apt-get update
COPY hmi.py /hmi.py
RUN apt-get install -y gcc python3-dev musl-dev python3-pip

RUN apt-get update
RUN pip3 install psycopg2-binary --break-system-packages
ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Europe/London
RUN apt-get install -y python3-tk

CMD sh -c "python3 hmi.py; sleep 1000;"
