FROM python:3.6-alpine
COPY attacker.py /attacker.py
RUN apk update && apk add postgresql-dev gcc python3-dev libpq-dev musl-dev
RUN apk update py-pip
RUN pip3 install psycopg2 --break-system-packages

CMD sh -c "python3 /attacker.py; sleep 1;"
